### ISSUE TITLE
如何使用spectator mode 来录制bot

### ISSUE THREAD

**Issue by redstarxz** [zju-vipa/Odyssey#3]
如题，项目启动后，如何通过spectator mode 查看bot，有没有相关的文档和教程？

**Comment by cshunzi** [comment]
这里提到的只是在录制视频时将自身玩家的游戏模式改为观察者模式。
在游戏设置内开启”作弊模式“，聊天框输入指令"/gamemode spectator"即可。
另外，可以使用"/tp bot"指令来传送到bot的位置。
This is only to change the game mode of the player to spectator mode. In the game settings, enable cheating and enter the command "/gamemode spectator" in the chat box. Additionally, you can use the "/tp bot" command to teleport to the bot's location.
