### ISSUE TITLE
What is the minimum configuration required for a fine-tuned model to run properly?

### ISSUE THREAD

**Issue by JoeyDD27** [zju-vipa/Odyssey#4]
RT

**Comment by aiwensiler** [comment]
You can find the environment requirements and reference usage code for our model on the Huggingface page [here](https://huggingface.co/Aiwensile2/MineMA-8B), or refer to the "Model Usage" section [here](https://github.com/zju-vipa/Odyssey/blob/master/MineMA-Model-Fine-Tuning/README.md) to get the usage steps.

**Comment by aiwensiler** [comment]
> RT

You can find the environment requirements and reference usage code for our model on the Huggingface page [here](https://huggingface.co/Aiwensile2/MineMA-8B), or refer to the "Model Usage" section [here](https://github.com/zju-vipa/Odyssey/blob/master/MineMA-Model-Fine-Tuning/README.md) to get the usage steps.
